name: Build Kernel with SUSFS
on:
  workflow_dispatch:
    inputs:
      CPU: {default: 'marble-s-oss', description: '分支'}
      FEIL: {default: 'marble_defconfig', description: '配置文件'}
      CPUD: {default: 'sm7475', description: '处理器代号'}
      ANDROID_VERSION: {default: 'android12', description: '内核安卓版本'}
      KERNEL_VERSION: {default: '5.10', description: '内核版本'}
      SUSFS_ENABLED: {default: true, description: '添加 SUSFS', type: boolean}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with: {root-reserve-mb: 8192, temp-reserve-mb: 2048, remove-dotnet: 'true', remove-android: 'true', remove-haskell: 'true', remove-codeql: 'true'}
      
      - name: Configure Git
        run: |
          git config --global user.name "build"
          git config --global user.email "3436378798@qq.com"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl gcc-aarch64-linux-gnu g++-aarch64-linux-gnu flex bison libssl-dev bc

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          git clone https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git -b ${{ inputs.CPU }} --depth=1
          cd Xiaomi_Kernel_OpenSource
          
          # 彻底清除 OnePlus 残留
          find . -name "Kconfig" -exec sed -i '/MMid/d' {} \;
          find . -name "Kconfig" -exec sed -i '/Mwid/d' {} \;
          rm -rf drivers/misc/MMid/ drivers/misc/Mwid/ 2>/dev/null || true
          sed -i 's/ -dirty//g' scripts/setlocalversion

      - name: Set up susfs
        if: ${{ inputs.SUSFS_ENABLED == 'true' }}
        run: |
          cd kernel_workspace/Xiaomi_Kernel_OpenSource
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }} --depth=1
          
          mkdir -p fs/sufs include/linux
          cp -r susfs4ksu/fs/sufs/* fs/sufs/ 2>/dev/null || :
          cp -r susfs4ksu/include/linux/* include/linux/ 2>/dev/null || :
          
          if [ ! -f "fs/sufs/Kconfig" ]; then
            touch fs/sufs/Kconfig
          fi

      - name: Fix Makefile and Kconfig
        run: |
          cd kernel_workspace/Xiaomi_Kernel_OpenSource
          
          # 最终清理
          sed -i '/source.*MMid/d' drivers/misc/Kconfig
          sed -i '/source.*Mwid/d' drivers/misc/Kconfig
          
          # 确保SUSFS引用存在
          if ! grep -q "fs/sufs/Kconfig" drivers/misc/Kconfig; then
            echo -e "\n# SUSFS Integration\nsource \"fs/sufs/Kconfig\"" >> drivers/misc/Kconfig
          fi
          
          # Makefile修复
          if ! grep -q "obj-y += sufs" fs/Makefile; then
            sed -i '/obj-y += /a obj-y += sufs/' fs/Makefile
          fi

      - name: Build kernel
        run: |
          cd kernel_workspace/Xiaomi_Kernel_OpenSource
          make O=out ARCH=arm64 ${{ inputs.FEIL }}
          make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: Make AnyKernel3
        run: |
          cd kernel_workspace
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cp Xiaomi_Kernel_OpenSource/out/arch/arm64/boot/Image ./AnyKernel3/
          
          # 添加sufs
          mkdir -p ./AnyKernel3/ramdisk/sbin
          if [ -f "Xiaomi_Kernel_OpenSource/susfs4ksu/bin/arm64/sufs" ]; then
            cp Xiaomi_Kernel_OpenSource/susfs4ksu/bin/arm64/sufs ./AnyKernel3/ramdisk/sbin/
          else
            curl -L https://gitlab.com/simonpunk/susfs4ksu/-/raw/main/bin/arm64/sufs -o ./AnyKernel3/ramdisk/sbin/sufs
          fi
          chmod 755 ./AnyKernel3/ramdisk/sbin/sufs
          
          # 启动脚本
          cat << EOF > ./AnyKernel3/ramdisk/init.sufs.rc
          service sufs-daemon /sbin/sufs --mount
              class main
              user root
              group root
              oneshot
          EOF
          echo 'import /init.sufs.rc' >> ./AnyKernel3/ramdisk/init.rc
          
          # 权限设置
          echo 'set_perm_recursive 0 0 0755 0755 "/sbin";' >> ./AnyKernel3/anykernel.sh
          echo 'set_perm 0 0 0755 "/sbin/sufs";' >> ./AnyKernel3/anykernel.sh
          sed -i '/device\.name1=/a device.name1=marble' ./AnyKernel3/anykernel.sh
          sed -i '/device\.name2=/a device.name2=marblein' ./AnyKernel3/anykernel.sh

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_SUSFS_marble
          path: ./kernel_workspace/AnyKernel3/*
